<?php
/**
 * Implementation of hook_menu
 */
function iczn_aker_menu() {
  $items = array();

  //List of open cases
  $new_cases = array(
    'title'            => 'New applications received but not published',
	'description'      => 'A list of cases received by the permission but not published',
	'page callback'    => 'iczn_aker_new_cases',
	'access arguments' => 'access content',
	'type'             => MENU_CALLBACK,
  );
  $items['new_cases'] = $new_cases;
  $items['content/new-applications-received-not-published'] = $new_cases; //Legacy
  
  return $items;
}


/**
 * List open cases
 */
function iczn_aker_new_cases() {
  return file_get_contents('http://aker.iczn.org/cases_recieved');
}