 <?php
/**
 * Provides integration between iczn.org and aker.iczn.org and case access by url: case/xxxx
 * Written by Ed Baker (http://ebaker.me.uk) for the ICZN (http://iczn.org)
 */
 
/**
 * Implementation of hook_menu
 */
function iczn_aker_menu() {
  //List of new cases
  $items['case'] = array(
        'title'            => 'Case information',
	    'description'      => 'List of ICZN Cases',
	    'page callback'    => 'iczn_aker_goto_case',
        'access callback'  => TRUE,
        'type'             => MENU_CALLBACK,
  );
  $items['cases/new'] = array(
        'title'            => 'New applications received but not yet published',
	    'description'      => 'A list of Cases received by the ICZN but not published',
	    'page callback'    => 'iczn_aker_new_cases',
        'access callback'  => TRUE,
        'type'             => MENU_CALLBACK,
  );
  
  //List of open cases
  $items['cases/open'] = array (
        'title'            => 'List of open Cases',
	    'description'      => 'List of open Cases',
	    'page callback'    => 'iczn_aker_open_cases',
        'access callback'  => TRUE,
        'type'             => MENU_CALLBACK,
  );
  
  return $items;
}


/**
 * List new cases
 */
function iczn_aker_new_cases() {
  return file_get_contents('http://aker.iczn.org/cases_recieved');
}

/**
 * List open cases
 */
function iczn_aker_open_cases() {
  return file_get_contents('http://aker.iczn.org/cases_open');
}

/**
 * Goto any case via URL case/xxxx
 */
function iczn_aker_goto_case()  {
  global $_GET;
  $args = explode('/', $_GET['q']);
  if (is_int($args[1])) {
    $case = $args[1];
  } else {
  	return '<p>Not a valid Case number</p>';
  }
  $term_name = 'Case '.$case;
  
  $results = taxonomy_get_term_by_name($term_name);
  
  //There should only be one
  $tid = $results[0]->tid;
  
  drupal_goto('taxonomy/term/'.$tid);
  
  return '<p>Failed to find Case</p>';
}